---
- name: Set fact force_install to no
  set_fact:
    force_install: no

- name: Set fact force_install to yes if downgrades are allowed
  set_fact:
    force_install: yes
  when: es_allow_downgrades

- name: Check if Elasticsearch is installed
  shell: "dpkg-query -W -f='${Status}' {{ es_package_name }}"
  register: elasticsearch_package
  failed_when: false
  changed_when: false
  check_mode: no

- name: Stop and remove Elasticsearch if already installed
  block:
    - name: Unhold Elasticsearch package
      dpkg_selections:
        name: "{{ es_package_name }}"
        selection: "install"
      when: elasticsearch_package.stdout == 'install ok installed'

    - name: Stop Elasticsearch service
      service:
        name: elasticsearch
        state: stopped
      when: elasticsearch_package.stdout == 'install ok installed'

    - name: Remove Elasticsearch package
      apt:
        name: "{{ es_package_name }}"
        state: absent
      when: elasticsearch_package.stdout == 'install ok installed'

- name: Copy Elasticsearch package to remote server
  copy:
    src: "files/{{ es_package_file }}"
    dest: "/tmp/{{ es_package_file }}"
    mode: '0644'

- name: Install Elasticsearch from local deb package
  apt:
    deb: "/tmp/{{ es_package_file }}"
    state: present
  register: elasticsearch_install_from_package
  notify: restart elasticsearch
  environment:
    ES_PATH_CONF: "{{ es_conf_dir }}"

- name: Hold Elasticsearch version if required
  dpkg_selections:
    name: "{{ es_package_name }}"
    selection: "hold"
  when: es_version_lock

- name: Clean up temporary files
  file:
    path: "/tmp/{{ es_package_file }}"
    state: absent
  when: elasticsearch_install_from_package.changed